theme: jekyll-theme-minimal
title: D365 Rapid Care
<<<<<<< HEAD
description: Rapid care for Dynamics 365 modules and devops. 
=======
description: Rapid care for Dynamics 365 modules and devops.
>>>>>>> 5accf6d055c180a6eca36d24208434109244f720
